export enum Permissao {
    ADICIONA_VENDEDOR = "ADICIONA_VENDEDOR",
    ADICIONA_GERENTE = "ADICIONA_GERENTE",
    ADICIONA_PILOTO = "ADICIONA_PILOTO",
    ADICIONA_AEROPORTO = "ADICIONA_AEROPORTO",
    LISTA_PILOTOS = "LISTAR_PILOTOS",
    ADICIONA_PRODUTO = "ADICIONA_PRODUTO"
}